version: "3"
services:
  apka:
    container_name: "NodeApp"
    build: 
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - Redis
  mongodb:
    image: mongo
    container_name: "MongoDB"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  Redis:
    image: redis
    container_name: "Redis"

